SYSTEM_TOOLCHAIN_ROOT := /work/sdk-toolchain/2015-11-3-for-ca/sdk_for_ca/cos_sdk_12_5

SYSTEM_CC := $(SYSTEM_TOOLCHAIN_ROOT)/toolchains/gcc/linux-x86_64/arm/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-gcc
SYSTEM_CXX := $(SYSTEM_TOOLCHAIN_ROOT)/toolchains/gcc/linux-x86_64/arm/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-g++
SYSTEM_AR := $(SYSTEM_TOOLCHAIN_ROOT)/toolchains/gcc/linux-x86_64/arm/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-ar

SYSTEM_CFLAGS := \
	-fno-exceptions \
	-Wno-multichar \
	-msoft-float \
	-fpie \
	-ffunction-sections \
	-fdata-sections \
	-funwind-tables \
	-fstack-protector \
	-Wa,--noexecstack \
	-Werror=format-security \
	-fno-short-enums \
	-march=armv7-a \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-include $(SYSTEM_TOOLCHAIN_ROOT)/include/system/core/include/arch/linux-arm/AndroidConfig.h \
	-mthumb-interwork \
	-DANDROID \
	-DCOS_SDK_VERSION=125 \
	-fmessage-length=0 \
	-W \
	-Wall \
	-Wno-unused \
	-Winit-self \
	-Wpointer-arith \
	-DHOST_BUILD=0 \
	-DTARGET_BUILD=1 \
	-Werror=return-type \
	-Werror=non-virtual-dtor \
	-Werror=address \
	-Werror=sequence-point \
	-DNDEBUG \
	-Wstrict-aliasing=2 \
	-fgcse-after-reload \
	-frerun-cse-after-loop \
	-frename-registers \
	-UDEBUG \
	-mthumb \
	-fomit-frame-pointer \
	-fno-strict-aliasing    \
	-fPIE \
	-D_USING_LIBCXX     \
	-MD \
	-DQCOM \
	-DGAIA \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/sdk/privilege/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/sdk/privilege/include/gaia   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/sdk/privilege/wrapper   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/gaia   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/memleak   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/system/core/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/common/frameworks/base/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/common/frameworks/base/native/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/common/hardware/libhardware/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/skia/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/skia/include/core   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/icu4c/common   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/icu4c/i18n   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/openssl/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/bluetooth/bluez/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/libcxx/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/gtest/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/gmock/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/opengl   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/json/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/libxml2/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/curl   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/libidn   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/external/libjingle   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libc/arch-arm   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libc/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libc/kernel/arch-arm   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libc/kernel/common   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libm   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libstdc++   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libthread_db   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libc/arch-arm/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libstdc++/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libc/kernel/common/asm-arm   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libm/include   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libm/include/arm   \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/bionic/libthread_db/include  \
	-I $(SYSTEM_TOOLCHAIN_ROOT)/include/system/core/include/arch/linux-arm/ \

SYSTEM_CPPFLAGS := \
	$(SYSTEM_CFLAGS) \
	-fvisibility-inlines-hidden \
	-Wsign-promo \
	-fpermissive \




SYSTEM_BINARYLDFLAGS := \
	-L$(SYSTEM_TOOLCHAIN_ROOT)/lib \
	-Wl,-rpath-link=$(SYSTEM_TOOLCHAIN_ROOT)/lib \
	-nostdlib \
	-Bdynamic \
	-pie \
	-Wl,-dynamic-linker,/system/bin/linker \
	-Wl,--gc-sections \
	-Wl,-z,nocopyreloc \
	-nodefaultlibs \
	-Wl,-z,noexecstack \
	-Wl,--icf=safe \
	-Wl,--fix-cortex-a8 \
	$(SYSTEM_TOOLCHAIN_ROOT)/lib/crtbegin_dynamic.o \
	$(SYSTEM_TOOLCHAIN_ROOT)/toolchains/gcc/linux-x86_64/arm/arm-linux-androideabi-4.8/bin/../lib/gcc/arm-linux-androideabi/4.8/armv7-a/libgcc.a \
	$(SYSTEM_TOOLCHAIN_ROOT)/lib/crtend_android.o


SYSTEM_SOLDFLAGS := \
	-L$(SYSTEM_TOOLCHAIN_ROOT)/lib \
	-Wl,-rpath-link=$(SYSTEM_TOOLCHAIN_ROOT)/lib \
	-nostdlib \
	-Wl,-soname,"libevent.so" \
	-Wl,--gc-sections \
	-Wl,-shared,-Bsymbolic \
	-nodefaultlibs \
	-Wl,--no-undefined \
	-Wl,-z,noexecstack \
	-Wl,--icf=safe \
	-Wl,--fix-cortex-a8 \
	$(SYSTEM_TOOLCHAIN_ROOT)/toolchains/gcc/linux-x86_64/arm/arm-linux-androideabi-4.8/bin/../lib/gcc/arm-linux-androideabi/4.8/armv7-a/libgcc.a \

SYSTEM_ARFLAGS := crsP

CC=${SYSTEM_CC}
CXX=${SYSTEM_CXX}
AR=${SYSTEM_AR}
CFLAGS=${SYSTEM_CFLAGS}
CPPFLAGS=${SYSTEM_CPPFLAGS}
LDFLAGS=${SYSTEM_SOLDFLAGS}
ARFLAGS = ${SYSTEM_ARFLAGS}

source := $(wildcard *.c)

all: libevent.so

%.o : %.c
	$(CC) -c $(CFLAGS) -I /home/werther/.tmux_config/libevent/include/ $< -o $@

%.o : %.cpp
	$(CXX) -c $(CPPFLAGS) $< -o $@

libevent.so : $(filter %.o, $(source:.c=.o))
	$(CC) $(CFLAGS) $^ $(LDFLAGS) -o $@
