#! /bin/bash
#
# dcrm.sh ---
#
# Filename: dcrm.sh
# Description:
# Author: Werther Zhang
# Maintainer:
# Created: Wed Jun  1 11:04:39 2016 (+0800)
#

# Change Log:
#
#

# defaultly remove exited container
tags="Exited"


#docker ps -a | grep '$tags' | awk '{print $1}' | xargs --no-run-if-empty docker rm
docker rm $(docker ps -q -f status=exited)
